### PR TITLE
chore: localisation fix for Help steps and topics

### LINKED ISSUE #664: [l10n] ESP: Help topics are unlocalized in Options
**Description**
 Help topics are unlocalized in Options in es_ES locale

**To Reproduce**
1. Install extension
2. Right click on extension > Options > scroll to Help topics

**Expected behavior**
Strings are localized

**Screenshots**
esp help topic
esp options
chs options

### PR DESCRIPTION
**Pull request by asthabh23**
Fix #664 

Tested with latest change, both Help Steps and Help Topics are now localised:

Help Step:
Captura de pantalla 2567-04-19 a las 4 02 31 p  m

Help Topics:
Captura de pantalla 2567-04-19 a las 4 01 09 p  m

### CODE REVIEW

File: src/extension/background.js [hunk 1]
```diff
@@ -330,7 +330,7 @@ function toggle(id) {
 function getHelpLanguage() {
   const uLang = chrome.i18n.getUILanguage();
   const lang = LANGS.find((l) => uLang.replace('-', '_') === l
-    || l.startsWith(uLang.split('_')[0])) || LANGS[0];
+    || l.startsWith(uLang.split('-')[0])) || LANGS[0];
```
Comment (rofe) [inline src/extension/background.js:333]: Hmm, because this worked fine before for other languages, and we don't have control over locale formats in different operating systems and browsers, I'd feel safer if we used a regexp with both `-` and `_` here:
```suggestion
    || l.startsWith(uLang.split(/[-_]/)[0])) || LANGS[0];
```

Comment (asthabh23) [reply src/extension/background.js:333]: Sure! Makes sense 👍🏻

**Review by rofe — APPROVED** [review]

**Review by rofe — APPROVED** [review]
