### PR TITLE
fix: send detail object to custom event listeners

### LINKED ISSUE #520: [options] missing placeholders for advanced project settings
image

### LINKED ISSUE #523: [regression] custom event listeners no longer get detail object
Caused by #497

### PR DESCRIPTION
**Pull request by rofe**
Fix #520 
Fix #523

### CODE REVIEW

**Review by tripodsan — APPROVED** [review]

File: src/extension/module.js [hunk 1]
```diff
@@ -888,14 +888,25 @@
...
-          data: data || {
-            config: JSON.parse(JSON.stringify(sk.config)),
-            location: sk.location,
-            status: sk.status,
-          },
+      const { config, location, status } = sk;
+      data = data || {
+        // turn complex into simple objects for event listener
+        config: JSON.parse(JSON.stringify(config)),
+        location: {
```
Comment (tripodsan) [inline src/extension/module.js:895]: or: json clone:

```
JSON.parse(JSON.stringify(window.location))
```

**Review by tripodsan — APPROVED** [review]

File: src/extension/module.js (hunk 1 above)
Comment (rofe) [reply src/extension/module.js:895]: It's not `window.location`, but a `URL` object, which won't let itself stringify.
