### PR TITLE
fix: validate production hostname

### LINKED ISSUE #591: [INTL]: Non latin symbol displayed like unicode in "Projects"
**Description**
The non-Latin character entered appears as Unicode in the "Production Hostname (optional)" and "Repository URL: https://github.com/...".
**To Reproduce**

1. Go to project folder
2. Click on extension button > "Add this project"
3. Click on extension button -> "Options"
4. Click "Edit" button in "Projects"
5. Enter non latin symbol example "繁" in "Production Hostname (optional)" or "Repository URL: https://github.com/..."
6. Click "Save"
7. Observe "Production"

Observe result: Non latin symbol displayed unicode not a symbol
Expected result: All symbol displayed correctly

https://github.com/adobe/helix-sidekick-extension/assets/144205585/929d48f7-57fe-493a-b57f-be39e2b27e7f

### PR DESCRIPTION
**Pull request by asthabh23**
#591 #595

### CODE REVIEW

**Review by rofe — CHANGES_REQUESTED** [review]
LGTM, but we should perform the same check on the advanced settings `previewHost` and `liveHost`.

File: src/extension/options.js [hunk 1]
```diff
@@ -209,6 +214,15 @@ function editProject(i) {
       }
     };
     const save = async () => {
+      const host = document.querySelector('#edit-host').value;
+      const previewHost = document.querySelector('#edit-previewHost').value;
+      const liveHost = document.querySelector('#edit-liveHost').value;
```
Comment (rofe) [inline src/extension/options.js:219]: Can you reuse these variables in the `input` object below?

**Review by rofe — CHANGES_REQUESTED** [review]

**Review by rofe — APPROVED** [review]

File: src/extension/options.js [hunk 2]
```diff
@@ -36,6 +36,11 @@ function isValidGitHubURL(giturl) {
     && Object.keys(getGitHubSettings(giturl)).length === 3;
 }
 
+function isValidProdHost(prodHost) {
+  const prodHostPattern = /^$|^(https?:\/\/)?([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}\/?/;
```
Comment (rofe) [inline src/extension/options.js:40]: I would not allow `https://` prefixes and trailing `/`s - we actually want domain/host names only

File: src/extension/options.js [hunk 3]
```diff
@@ -36,6 +36,11 @@ function isValidGitHubURL(giturl) {
     && Object.keys(getGitHubSettings(giturl)).length === 3;
 }
 
+function isValidProdHost(prodHost) {
```
Comment (rofe) [inline src/extension/options.js:39]: I think this should be changed to `isValidHost(host)` now that we are using it to validate other hosts as well.

**Review by rofe — CHANGES_REQUESTED** [review]

**Review by rofe — APPROVED** [review]
