### PR TITLE
fix: differentiate between file and folder in sharepoint

### LINKED ISSUE #536: detect asset view in sharepoint and switch out of admin mode
When navigating to an image in SharePoint, the sidekick remains in admin mode, prevcenting the user from previewing the file. 

Expectation: The sidekick can tell files from folders and react accordingly while the user is navigating through SharePoint.

### PR DESCRIPTION
**Pull request by rofe**
Fix #536

### CODE REVIEW

**Comment by rofe** [comment]
Changes made in this PR to address the issue:
- consolidate/extend the sharepoint URL detection to be able to better distinguish between folders, viewers and editors
- add a check for supported file extensions
- move the check for `window.location` changes from the bulk plugins to the `Sidekick` level
- switch selection change detection from interval to `click/keyup` listeners (and adjust tests to dispatch click events)
- improve/fix custom plugin override condition checks
- always evaluate custom plugin `includePaths/excludePaths` against the resolved `webPath` instead of the current location
- refactor plugin re-evaluation on `statusfetched`

File: src/extension/module.js [hunk 1]
```diff
@@ -407,6 +407,93 @@
...
 
+  /**
+   * Checks a path against supported file extensions.
+   * @private
+   * @param {string} path The path to check
+   * @returns {boolean} {@code true} if file extension supported, else {@code false}
+   */
+  function isSupportedFileExtension(path) {
+    const file = path.split('/').pop();
+    const extension = file.split('/').pop().split('.').pop();
```
Comment (tripodsan) [inline src/extension/module.js:418]:
```suggestion
    const extension = file.split('.').pop();
```
